// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_MdSqrwgxTsgTxiOKoTP3XDYq3E7vHZg',
    appId: '1:420283172546:web:e591c58369b9aeb2675d5b',
    messagingSenderId: '420283172546',
    projectId: 'ecommerceapp-eb78a',
    authDomain: 'ecommerceapp-eb78a.firebaseapp.com',
    storageBucket: 'ecommerceapp-eb78a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD37II6FezRKNjwT0addb2y07HS28u8kAw',
    appId: '1:420283172546:android:d6a8dd3f7c73bc0a675d5b',
    messagingSenderId: '420283172546',
    projectId: 'ecommerceapp-eb78a',
    storageBucket: 'ecommerceapp-eb78a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpDdDh3YY6Wnx92tkLjlFY-DS6hjZe9cQ',
    appId: '1:420283172546:ios:50be65438dec46b1675d5b',
    messagingSenderId: '420283172546',
    projectId: 'ecommerceapp-eb78a',
    storageBucket: 'ecommerceapp-eb78a.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpDdDh3YY6Wnx92tkLjlFY-DS6hjZe9cQ',
    appId: '1:420283172546:ios:ec5934d9beaf80d7675d5b',
    messagingSenderId: '420283172546',
    projectId: 'ecommerceapp-eb78a',
    storageBucket: 'ecommerceapp-eb78a.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
